Vagrant.configure(2) do |config|

    config.vm.box = "ubuntu/jammy64"

    config.vm.box_check_update = false
  
    config.vm.define "server-php" do |subconfig|

      subconfig.vm.provider "virtualbox" do |vb|
        vb.name = "server-php"

      end

      subconfig.vm.hostname = "srv-php"
      subconfig.vm.network "public_network", ip: "10.114.255.250", bridge: "wlo1"

    end

  end
  